######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 24 23:16:18 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
RESOURCES = rez.qrc
# Input
HEADERS += effect_window.h
SOURCES += effect.cpp effect_window.cpp
