######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 20 14:12:26 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += test_window.h
SOURCES += test.cpp test_window.cpp
