######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 24 01:55:06 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += calc_window.h
SOURCES += calc_window.cpp main.cpp
