######################################################################
# Automatically generated by qmake (2.01a) Sat May 10 21:05:35 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += kmp_highscore.h kmp_info.h kmp_op.h kmp_window.h mp.h
SOURCES += kmp.cpp \
           kmp_highscore.cpp \
           kmp_info.cpp \
           kmp_op.cpp \
           kmp_window.cpp \
           mp.cpp
